POST http://localhost:3003/buyers 
Content-Type: application/json

{
    "name": "Rogério",
    "email": "rogerio@gmail.com",
    "cpf": 78945614587
}
###
POST http://localhost:3003/clients
Content-Type: application/json
###

POST http://localhost:3003/payment/c631ee49-04a4-465d-ae57-dda0024fa12d/0f6469af-2518-49ac-8e64-02b495423046
Content-Type: application/json

{
    "amount": 1200,
    "type": "BOLETO",
    "card_holder": "Paloma", 
    "card_number": 753159, 
    "card_expiration_date": "fhhh",
    "card_cvv": 8563
}
###

GET http://localhost:3003/payment/626ec7e2-b461-4261-9361-84cf5612d4e8/da4ad440-3043-4999-9ea6-ad49c0ae333d