POST http://localhost:3003/buyers 
Content-Type: application/json

{
    "name": "Roberval",
    "email": "roro@gmail.com",
    "cpf": "85278995188"
}
###
POST http://localhost:3003/clients
Content-Type: application/json
###

POST http://localhost:3003/payment/b624c8c8-5531-42b8-9e73-38ce538f7383/da4ad440-3043-4999-9ea6-ad49c0ae333d
Content-Type: application/json

{
    "amount": 580,
    "type": "CARTÃO DE CRÉDITO",
    "card_holder": "Roberval", 
    "card_number": 852741963, 
    "card_expiration_date": "02/2028",
    "card_cvv": 456
}
###

GET http://localhost:3003/payment/626ec7e2-b461-4261-9361-84cf5612d4e8/da4ad440-3043-4999-9ea6-ad49c0ae333d